version: '3.8'
services:
  mit-service: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: mit-service
    container_name: mit-service
    depends_on:
      - mongodb_container
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongodb_container
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
